### ISSUE TITLE
Support for Carthage

### ISSUE THREAD

**Issue by marekcirkos** [mattstevens/RoutingHTTPServer#20]
It would be cool if you could add support for Carthage.
https://github.com/Carthage/Carthage#supporting-carthage-for-your-framework

**Comment by colemancda** [comment]
Ok... I don't see a pull request. You can make the appropriate changes in a fork and I will be happy to add them.

**Comment by marekcirkos** [comment]
https://github.com/mattstevens/RoutingHTTPServer/pull/21
