### ISSUE TITLE
iOS 6 and OS X 10.8 compatibility

### ISSUE THREAD

**Issue by awein** [mattstevens/RoutingHTTPServer#5]
Compiling on OS X 10.8 or iOS 6 will fail:

`error: 'release' is unavailable: not available in automatic reference counting mode`

`dispatch_release` must not be used on OS X >=10.8 and iOS 6

see this discussion for further information:
http://stackoverflow.com/questions/8618632/does-arc-support-dispatch-queues

**Comment by mattstevens** [comment]
Thanks for letting me know, I hadn't been running with a deployment target this high yet.
