### ISSUE TITLE
Have you used this Server to implement DLNA?

### ISSUE THREAD

**Issue by allenhsu** [mattstevens/RoutingHTTPServer#7]
Recently I'm working on a project to server music from iPhone's library to DLNA supported device. Doing some search I came to your project. I'm wondering if you have implemented DLNA server with this project?

Sorry for my poor English.

**Comment by mattstevens** [comment]
Yes, I've been using this project in a [Mac DLNA Server](http://www.alloysoft.com/blog/introducing-onscreen) for a couple years now and it has worked out well.
